spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

